-- changeset camtien:13
INSERT INTO catalog (catalog_name) VALUES 
    ('Hair'),
    ('Nails'),
    ('Skin'),
    ('Spa'),
    ('Makeup'),
    ('Lips');
-- rollback DELETE FROM catalog WHERE catalog_name IN ('Hair', 'Nails', 'Skin', 'Spa', 'Makeup', 'Lips');

-- changeset camtien:14
INSERT INTO shops (shop_name, owner_id, address, phone, email, latitude, longitude, created_at, updated_at, image) VALUES
('Nail Palace', 
 (SELECT user_uuid FROM users WHERE username = 'user2'), 
 '456 Nail Ave, Los Angeles, CA', 
 '0987654321', 
 'nailpalace@example.com', 
 34.052235, 
 -118.243683, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 'nail_palace.jpg'),

('Glow Spa', 
 (SELECT user_uuid FROM users WHERE username = 'user3'), 
 '789 Spa Blvd, Los Angeles, CA', 
 '1231231234', 
 'glowspa@example.com', 
 34.052235, 
 -118.243683, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 'glow_spa.jpg'),

('Relax Spa', 
 (SELECT user_uuid FROM users WHERE username = 'user4'), 
 '321 Relax Rd, Los Angeles, CA', 
 '3213213210', 
 'relaxspa@example.com', 
 34.052235, 
 -118.243683, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 'relax_spa.jpg'),

('Makeup Studio', 
 (SELECT user_uuid FROM users WHERE username = 'user5'), 
 '654 Makeup St, Los Angeles, CA', 
 '4564564567', 
 'makeupstudio@example.com', 
 34.052235, 
 -118.243683, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 'makeup_studio.jpg'),

('Beauty Clinic', 
 (SELECT user_uuid FROM users WHERE username = 'user6'), 
 '987 Beauty Ave, Los Angeles, CA', 
 '5675675678', 
 'beautyclinic@example.com', 
 34.052235, 
 -118.243683, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 'beauty_clinic.jpg');

-- rollback DELETE FROM shops WHERE shop_name IN ('Nail Palace','Glow Spa','Relax Spa','Makeup Studio','Beauty Clinic');


-- changeset camtien:15
INSERT INTO services (service_name, shop_uuid, catalog_uuid, description, price, duration, created_at, updated_at) VALUES 
('Haircut', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Salon Glamour' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Hair' LIMIT 1), 
 'A stylish haircut to refresh your look.', 
 25.00, 
 30, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Manicure', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Nail Palace' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Nails' LIMIT 1), 
 'Professional manicure for beautiful nails.', 
 15.00, 
 45, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Facial Treatment', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Glow Spa' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Skin' LIMIT 1), 
 'Deep cleansing facial for healthy skin.', 
 50.00, 
 60, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Body Massage', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Relax Spa' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Spa' LIMIT 1), 
 'Relaxing body massage to relieve stress.', 
 70.00, 
 90, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Makeup Application', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Makeup Studio' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Makeup' LIMIT 1), 
 'Professional makeup application for special events.', 
 40.00, 
 60, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Lip Fillers', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Beauty Clinic' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Lips' LIMIT 1), 
 'Enhance your lips with fillers.', 
 300.00, 
 30, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Pedicure', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Nail Palace' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Nails' LIMIT 1), 
 'Pamper your feet with a relaxing pedicure.', 
 20.00, 
 45, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Hair Coloring', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Salon Glamour' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Hair' LIMIT 1), 
 'Professional hair coloring for a new look.', 
 80.00, 
 120, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Bridal Makeup', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Makeup Studio' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Makeup' LIMIT 1), 
 'Bridal makeup to make your day special.', 
 150.00, 
 120, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Aromatherapy', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Relax Spa' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Spa' LIMIT 1), 
 'Aromatherapy session for relaxation and rejuvenation.', 
 60.00, 
 60, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP);

-- rollback DELETE FROM services WHERE service_name IN ('Hair Cut','Nail Art','Facial Treatment','Full Body Massage','Makeup Application','Pedicure','Hair Coloring','Skin Treatment','Eyebrow Shaping','Manicure');
