class Message():
    _success = "Success"
    _not_found = "Không tìm thấy thông tin"
    _no_content = "Không có dữ liệu"
    _server_error = "Lỗi server"
    _file_sucess = "Upload file thành công"
    _file_error = "Upload file thất bại"
    _create_error = "Tạo không thành công"
    _no_authenticate = "Chưa được xác thực"
    _no_permission = "Không có quyền thực thi"
    _no_user_founded = "don't existing user"
    _invalid_credentials = "Invalid Credentials"
    _user_exist = "User exist"
    _delete_user_success = "Delete user successfully"
    _delete_user_fail = "Delete user failed"
    _update_user_success = "Update user successfully"
    _update_user_fail = "Update user failed"
