-- changeset camtien:60
INSERT INTO services (service_name, shop_uuid, catalog_uuid, description, price, duration, created_at, updated_at,employees) 
VALUES 
('Haircut', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Salon Glamour' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Hair' LIMIT 1), 
 'A stylish haircut to refresh your look.', 
 25.00, 
 30, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 5),

('Manicure', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Nail Palace' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Nails' LIMIT 1), 
 'Professional manicure for beautiful nails.', 
 15.00, 
 45, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 3),

('Facial Treatment', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Glow Spa' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Skin' LIMIT 1), 
 'Deep cleansing facial for healthy skin.', 
 50.00, 
 60, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP,2),

('Body Massage', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Relax Spa' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Spa' LIMIT 1), 
 'Relaxing body massage to relieve stress.', 
 70.00, 
 90, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP,4),

('Makeup Application', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Makeup Studio' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Makeup' LIMIT 1), 
 'Professional makeup application for special events.', 
 40.00, 
 60, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP,5),

('Lip Fillers', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Beauty Clinic' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Lips' LIMIT 1), 
 'Enhance your lips with fillers.', 
 300.00, 
 30, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP,3),

('Pedicure', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Nail Palace' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Nails' LIMIT 1), 
 'Pamper your feet with a relaxing pedicure.', 
 20.00, 
 45, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP,2),

('Hair Coloring', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Salon Glamour' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Hair' LIMIT 1), 
 'Professional hair coloring for a new look.', 
 80.00, 
 120, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP,5),

('Bridal Makeup', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Makeup Studio' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Makeup' LIMIT 1), 
 'Bridal makeup to make your day special.', 
 150.00, 
 120, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP,4),

('Aromatherapy', 
 (SELECT shop_uuid FROM shops WHERE shop_name = 'Relax Spa' LIMIT 1), 
 (SELECT catalog_uuid FROM catalog WHERE catalog_name = 'Spa' LIMIT 1), 
 'Aromatherapy session for relaxation and rejuvenation.', 
 60.00, 
 60, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP,4);
