class Message():
    _success = "Success"
    _error = "Somthing error"
    _not_found = "Không tìm thấy thông tin"
    _no_content = "Không có dữ liệu"
    _server_error = "Lỗi server"
    _file_sucess = "Upload file thành công"
    _file_error = "Upload file thất bại"
    _no_authenticate = "Chưa được xác thực"
    _no_permission = "Không có quyền thực thi"
